### PR TITLE
v2.10.0 Nightly

### LINKED ISSUE #1443: Add CurSearch to default_theme
### Is your feature related to a problem?

_No response_

### Describe the new feature

To help distinguish the current search item over the other matches, setting the highlight CurSearch helps. I'd submit as a PR except you know the color palette better than I do, although, looking through the colors, orange looked like it might be nice.

### Additional context

_No response_

### LINKED ISSUE #1445: Windows bootstrap fails
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Windows 10

### Describe the bug

When you clone the github repo (main branch) and use the default configs, just opening neovim starts the plugin installation.
When it seems to have finished, the message "All parsers are up-to-date!" appears at the bottom and all the plugins have a check ✓ but `telescope-fzf-native.nvim`, which has a ⟳ (my font doesn't seem to have an icon for it).
It also displays this message
imagen

Now, if I close neovim and open it again, this error message pops up
```
Se ha detectado un error al procesar C:\Users\raul\AppData\Local\nvim\init.lua:
Failed to load core.bootstrap

...\site\pack\packer\start\impatient.nvim/lua/impatient.lua:95: Could not hash C:\Users\raul\AppData\Local\nvim-data/packer_compiled.lua
Pulse INTRO o escriba una orden para continuar
```
And indeed packer_compiled.lua does not exist on my nvim-data folder.

This also breaks my user configuration as I can't run `nvim --headles blah blah` because it will never end.

The only way I have found to go around this and use it is to:
1. Delete the just created `nvim-data` folder
2. Rerun nvim and wait untill all plugins are synchronized
3. Instead of closing neovim, run `:PackerCompile`
4. Now close neovim and it will be working

### Steps to Reproduce

1. Clear previous config and data
2. Clone repository
3. Run `nvim`
4. Close neovim when it "finishes"
5. Reopen `nvim`

### Expected behavior

To generate a packer_compiled.lua

### Screenshots

_No response_

### Additional Context

_No response_

### LINKED ISSUE #1447: PackerSync trying to upgrade nvim-window-picker to version 1.5 everytime
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.9.1

### Neovim version (>= 0.8)

NVIM v0.8.1

### Operating system/version

Fedora 37

### Describe the bug

:PackerSync always think nvim-window-picker needs to be updated.

```
✓ Updated s1n7ax/nvim-window-picker: a53a3b7..5902827
 URL: https://github.com/s1n7ax/nvim-window-picker
 Commits:
   5902827 refactor: change use_cmd config to show_prompt (il y a 3 jours)
   d65aaad feat: add option "use_cmd" to show or not message in cmdline (il y a 8 jours)
   93cfc88 Merge pull request #24 from adoyle-h/feat/selection_display (il y a 4 semaines)
   f80963b feat: add option "selection_display" to change display (il y a 5 semaines)
```

### Steps to Reproduce

clean your install : 
```
rm -rf ~/.local/site/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```
Launch neovim, let it install everything, exit.

Reopen neovim.

:PackerSync will result in 1 update on nvim-window-picker

close neovim, repeat ... 

### Expected behavior

We are using [v1.4](https://github.com/s1n7ax/nvim-window-picker/releases/tag/v1.4) version (a53a3b7) PackerSync should not try to pull the [1.5](https://github.com/s1n7ax/nvim-window-picker/releases/tag/v1.5) version (5902827) or is the update silently failing and i'm not aware of ?

### Screenshots

_No response_

### Additional Context

_No response_

### LINKED ISSUE #1448: No way to recover unsaved file contents
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.9.1

### Neovim version (>= 0.8)

v0.8.1

### Operating system/version

macOS Ventura 13.0

### Describe the bug

Hi! I recently installed NeoVim along with AstroVim. 

I was editing a file this morning when I accidentally pressed CMD + W (macOS), thus closing my terminal instance (iTerm2).
Upon reopening my file. I noticed I had lost all my changes (forgot to press CTRL + S to save).

The `:rec` command did not work.
There isn't a `main.rs~` edit file nor a `.swp` file.

### Steps to Reproduce

1. open iTerm2 on macOS ventura 13.0
2. open a `main.rs` in a Rust project (initialised using `cargo new <name_of_the_project>` and `cd` into it.
3. start editing it
4. press CMD + W before saving the file.

### Expected behavior

I expected to be able to recover my unsaved changes.

### Screenshots

_No response_

### Additional Context

I have not created a new user config. I'm using the default AstroVim configuration.

### PR DESCRIPTION
**Pull request by mehalter**
Resolves #1443 
Resolves #1445
Resolves #1447 
Resolves #1448

# What's New

- Add `<leader>lI` mapping to view Null-ls info
- Add `]t` and `[t` mappings to navigate between tabs
- Add `\` and `|` mappings to make horizontal and vertical splits respectively
- Add `heirline.attributes` and `heirline.icon_highlights` tables to allow easily customizing Heirline elements in statusline/winbar/bufferline
- Add new Heirline based bufferline using the new `astronvim.status` API that is used in the `statusline` and `winbar`
  - This feature is opt-in and can be enabled in the `options.g` table with `heirline_bufferline = true` (must run `:PackerSync` afterwards to remove bufferline.nvim
  - [Documentation on enabling Heirline based bufferline](https://astronvim.github.io/Recipes/status#heirline-based-bufferline)
- Don't disable `swapfile` by default (Can be disabled in the `options.opt` table with `swapfile = false`)
- Improved default theme highlights for DAP UI

### CODE REVIEW

**Comment by gwww** [comment]
I just tested nightly and I'm getting completions showing up in telescope. I was using find files where it showed up. I switch back to 2.9.1 and the completions in telescope go away (as desired and expected).

**Comment by mehalter** [comment]
@gwww I can't replicate this

**Comment by gwww** [comment]
Apologies, found error in my config. Suggestion though. What happened is that I was stopping cmp from showing when typing comments, which seems like a it could be a good add to the cmp enabled function. This is what I have:
```
    return not (context.in_treesitter_capture("comment") == true or context.in_syntax_group("Comment"))
```

File: lua/configs/heirline.lua [hunk 1]
```diff
@@ -107,6 +206,54 @@ local heirline_opts = astronvim.user_plugin_opts("plugins.heirline", {
...
+              minwid = function(self) return self.bufnr end,
+              name = "heirline_tabline_close_buffer_callback",
+            },
+          },
+          padding = { left = 1, right = 1 },
+          hl = function(self)
+            return {
+              fg = self.is_active and "tab_fg" or "tab_inactive_fg",
+              bold = self.is_active,
+              italic = self.is_active,
```
Comment (gwww) [inline lua/configs/heirline.lua:237]: Is there a way to control the bold/italic choice? I did see `user_plugin_opts` being called to control these options.

Comment (mehalter) [reply lua/configs/heirline.lua:237]: Yup! You can customize it just like the statusline using the status API we provide. Here is my own personal customer bufferline that disables the close button as an example: https://code.mehalter.com/AstroNvim_user/~files/master/plugins/heirline.lua

Comment (mehalter) [reply lua/configs/heirline.lua:237]: Everything can be configured completely from the `plugins.heirline`

Comment (gwww) [reply lua/configs/heirline.lua:237]: Thanks, I understand now. Because the config is a parameter to a function am I right in thinking that the entire bit of that config must be replicated except for the bit to be modified? 

So, `astronvim.status.heirline.make_buflist(astronvim.status.component.file_info {...}` the entire table must be populated.

Comment (mehalter) [reply lua/configs/heirline.lua:237]: Yup!

Comment (gwww) [reply lua/configs/heirline.lua:237]: I think you are following me! So to remove the `italic` setting I replicate all of `config[3][2]` and remove the italic line. It would be nice if there was a simpler way of doing that, which admittedly I don't know what that is.

Some of what I'm thinking here is v3 stuff, but let me spit ball a concept. Don't know if it's consistent with the philosophy of the framework, but let me try.

For readability, change here: https://github.com/AstroNvim/AstroNvim/blob/nightly/lua/configs/heirline.lua#L164-L165 to:
```
local heirline_opts = astronvim.user_plugin_opts("plugins.heirline", {
  statusline = {...},
  winbar = {...},
  bufferline = {...},
}
heirline.setup(heirline_opts.statusline, heirline_opts.winbar, heirline_opts.bufferline)
```

In each of the 3 sections above, keep what is in the table unchanged (the ... stuff), except add another table, perhaps called `opts` or `astro_opts`. Then add a whatever "tweaking" options that would be useful, like say `italic` ;)  So for example we end up with:
```
local heirline_opts = astronvim.user_plugin_opts("plugins.heirline", {
  ...
  bufferline = {
    astro_opts = {
      italic = false,
    }
  }
}
```
Anyway, I hope this provokes some thoughts. Much of the other config are tables being passed into functions and single entries in those tables can be modified so the user ends up with a "tweaked" config. In the bufferline case the tweaking is a function that has substantial enough logic that I'm repeating core framework code.

Comment (mehalter) [reply lua/configs/heirline.lua]: @gwww the latest push exposes a bunch of new options to help the user easily fine tune styles ! It isn't done through the `plugins.heirline` table since that strays from the philosophy of `plugins.X = {}` should directly overwrite the `require("X").setup({})` call. We have put it into a new table called `heirline.bufferline` in `user/init.lua` (or `user/heirline/bufferline.lua` file if splitting up config):

All Options:

```lua
return {
  heirline = {
    bufferline = {
      -- true, false, or conditional function to calculate when to color filetype icons
      -- example to color only active and visible buffers:
      -- color_icons = function(self) return self.is_active or self.is_visible end
      color_icons = true,
      -- styling choices for each element, check possible attributes with `:h attr-list`
      buffer = {},
      buffer_path = {},
      buffer_close = {},
      buffer_visible = {},
      buffer_visible_path = {},
      buffer_visible_close = {},
      buffer_active = { bold = true, italic = true },
      buffer_active_path = {},
      buffer_active_close = {},
      buffer_picker = { bold = true },
      buffer_overflow = {},
      tab = {},
      tab_active = {},
      tab_close = {},
    },
  },
}
```

For example, if you wanted to disable the italics for the active buffer, you would simply need this:

```lua
return {
  heirline = {
    bufferline = {
      buffer_active = { italic = false },
    },
  },
}
```

the `color_icons` one is nice as well, it either lets you enable/disable filetype icon colors with a boolean (true/false) or you can do it with a conditional function. So if you wanted to only color the filetype icons for active or visible buffers:

```lua
return {
  heirline = {
    bufferline = {
      color_icons = function(self) return self.is_active or self.is_visible end
    },
  },
}
```

Comment (mehalter) [reply lua/configs/heirline.lua]: Let me know what you think of this @gwww :) Tried to get some easy tweaking added into the setup while still aligning with the philosophy

Comment (gwww) [reply lua/configs/heirline.lua]: I like the approach, although I have not got it to work yet. I created `user/heirline/bufferline.lua` with the disable italic example above and I'm still getting italics. I'm still playing and will read code further to see what is going on (i.e.: what I messed up!).

For a moment, looking at the bigger picture, it feels like config is split oddly. For example, I now have (assuming I've got the right path):
- `user/plugins/heirline.lua` to tweak my statusline
- `user/heirline/bufferline.lua` to tweak my bufferline

I understand how it got this way, feels like an inconsistent story (philosophy) being told. Does that make sense?

Comment (mehalter) [reply lua/configs/heirline.lua]: If you want to modify the structure of the statusline, winbar, or tabline then you will need to modify `plugins.heirline`. 

If you want to modify exposed options they will go into `heirline.X` we currently have: `heirline.colors`, `heirline.separators`, and `heirline.bufferline`.

You said you haven't figured out how to make it work yet, what's currently in your file for changing it?

Comment (mehalter) [reply lua/configs/heirline.lua]: @gwww if you are putting it into a separate file (`user/heirline/bufferline.lua`) then it should look like this:

```lua
return {
  buffer_active = { italic = false },
}
```

Comment (mehalter) [reply lua/configs/heirline.lua]: Maybe we should change it to be more general and add styles to the statusline elements: thinking 🤔 then we have colors and styles to go with each color

Comment (gwww) [reply lua/configs/heirline.lua]: I was also thinking about the `highlight` functionality, then **styling** *[line|bar] is just like other stuff. There will still be other options, such as `color_icons` that will have to fit into the config.

BTW, I did get mine working... I haven't had much time to look at anything today. I had a typo.

Comment (mehalter) [reply lua/configs/heirline.lua]: @gwww just a heads up, I revised the previous commit and moved it to `heirline.attributes` so you will need to rename your `heirline/bufferline.lua` file to `heirline/attributes.lua`. I still need to rework the options like `color_icons` to fit nicely into the philosophy, but this now works for all element names :)

File: lua/core/utils/status.lua [hunk 2]
```diff
@@ -737,9 +758,18 @@ end
...
+        if type(color_icons) == "function" then color_icons = color_icons(self) end
+        if color_icons then return astronvim.status.hl.filetype_color(self) end
+      end,
+    },
+    unique_path = {
+      hl = function(self) return astronvim.status.hl.get_attributes(self.tab_type .. "_path") end,
+    },
     close_button = {
-      hl = function(self) return { fg = self.tab_type .. "_close_fg" } end,
+      hl = function(self) return astronvim.status.hl.get_attributes(self.tab_type .. "close") end,
```
Comment (gwww) [inline lua/core/utils/status.lua:772]: This should be `_close`. I get the following error when starting:
```
E5108: Error executing lua ...ack/packer/opt/heirline.nvim/lua/heirline/highlights.lua:33: 'buffer_activeclose_fg' is not a valid color
```

Comment (mehalter) [reply lua/core/utils/status.lua]: ah thanks for catching this. Just revised the commit

File: lua/configs/heirline.lua (hunk 1 above)
Comment (mehalter) [reply lua/configs/heirline.lua]: @gwww ok, I just finished cleaning this up. Here is an example of the current `heirline` table options

```lua
  -- Customize Heirline options
  heirline = {
    -- Customize different separators between sections
    separators = {
      tab = { "", "" },
    },
    -- Customize colors for each element each element has a `_fg` and a `_bg`
    colors = function(colors)
      colors.git_branch_fg = astronvim.get_hlgroup "Conditional"
      return colors
    end,
    -- Customize attributes of highlighting in Heirline components
    attributes = {
      -- styling choices for each heirline element, check possible attributes with `:h attr-list`
      git_branch = { bold = true }, -- bold the git branch statusline component
      buffer_active = { italic = false }, -- disable italic of active buffer
    },
    -- Customize if icons should be highlighted
    icon_highlight = {
      -- disable highlighting LSP symbols in the breadcrumbs
      breadcrumbs = false,
      file_icon = {
        -- highlight filetype icon in the statusline
        statusline = true,
        -- Only color tabline filetype icons if the buffer is active or visible
        tabline = function(self) return self.is_active or self.is_visible end, 
      },
    },
  },
```

Comment (mehalter) [reply lua/configs/heirline.lua]: @gwww just a heads up I renamed the `icon_highlight` table to `icon_highlights` to match the rest of the plurality in the names

Comment (gwww) [reply lua/configs/heirline.lua]: Thx
