### PR TITLE
AstroNvim v4: the devs are getting lazy

### LINKED ISSUE #2180: Move global neoconf.json outside of `lua/` folder
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Linux Mint 21.1

### Terminal/GUI

Alacritty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.34.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- WARNING `node` is not installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Following is the path generated for neoconf global settings path

I added following print statement to `lua/plugins/lsp.lua:38`

```lua
{
    "folke/neoconf.nvim",
    opts = function()
    --
    --

      vim.print(">>", global_settings and string.rep("../", depth):sub(1, -2) .. global_settings)
      return { global_settings = global_settings and string.rep("../", depth):sub(1, -2) .. global_settings }
    end,
  }
```

Result:
```
>>
../../../../home/s1n7ax/.config/astronvim/lua/user/neoconf.json
```

### Steps to Reproduce

1. Add neoconf.json to `~/.config/astronvim/lua/user/neoconf.json`
2. Add following content to the file
```json
{
  "neodev": {
    "library": {
      "enabled": true,
      "plugins": true
    }
  },
  "neoconf": {
    "plugins": {
      "lua_ls": {
        "enabled": true
      }
    }
  },
  "lspconfig": {
    "lua_ls": {
      "Lua.format.enable": false
    }
  }
}
```
3. Open a project with a `.lua` file `mkdir test && cd test && git init && nvim test.lua`
4. Add some content
5. move the cursor to first line
6. `:vsp` split window and move the cursor to last line
7. Jump back to first window and run `:Format`

### Expected behavior

Expected:
Cursor in the new window should still be at last line

Actual:
File resets and cursor pos jumps to first line

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mehalter**
## Release Checklist

- [x] Update `lazy_snapshot.lua`
- [ ] Release v4 documentation
- [ ] Archive [AstroNvim/user_example](https://github.com/AstroNvim/user_example)

Closes #2180

### CODE REVIEW

File: lua/astronvim/init.lua [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+    if vim.notify ~= notify_queue then replay() end
+  end)
+  -- or if it took more than 500ms, then something went wrong
+  timer:start(500, 0, replay)
+end
+
+function M.init()
+  if vim.fn.has "nvim-0.9" == 0 then
+    vim.api.nvim_echo({
+      { "AstroNvimVim requires Neovim >= 0.9.0\n", "ErrorMsg" },
```
Comment (2giosangmitom) [inline lua/astronvim/init.lua:38]:
```suggestion
      { "AstroNvim requires Neovim >= 0.9.0\n", "ErrorMsg" },
```

Comment (mehalter) [reply lua/astronvim/init.lua]: Thanks! Resolved in the commit
