### PR TITLE
3.10.0 Nightly

### LINKED ISSUE #1750: Status `unique_path` not accurate if child file opened before parent
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

Alacritty 

### AstroNvim Health

1
  1 astronvim: require("astronvim.health").check()
  2 ========================================================================
  3 ## AstroNvim
  4   - INFO: AstroNvim Version: v3.8.0
  5   - INFO: Neovim Version: v0.8.3
  6   - OK: Using stable Neovim >= 0.8.0
  7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
  8   - OK: `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
 10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
 11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
 12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
 13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I configured the status line as following: 

```lua
local M = {}

local function config(_, opts)
    local status = require("astronvim.utils.status")
    opts.statusline = {
        hl = { fg = "fg", bg = "bg" },
        status.component.mode({
            mode_text = { padding = { left = 1, right = 1 } },
        }), -- add the mode text
        status.component.git_branch(),
        status.component.file_info({
            unique_path = {},
        }),
        status.component.cmd_info(),
        status.component.git_diff(),
        status.component.diagnostics(),
        status.component.fill(),
        status.component.cmd_info(),
        status.component.fill(),
        status.component.lsp(),
        status.component.treesitter(),
        status.component.nav(),
        -- remove the 2nd mode indicator on the right
    }

    -- return the final configuration table
    return opts
end

M.config = config

return M
```

I have  multiple `init.lua` files.

If I open the parent init.lua file first and then the `config/init.lua` file, everything works as expected. The status line shows the `config/init.lua` and just `init.lua`.

But if I open `config/init.lua` file and then `init.lua` they both show just `init.lua`

However the tabline on top always shows the correct information.

### Steps to Reproduce

See description of bug and video below for reproduction 

https://user-images.githubusercontent.com/1775346/230785263-fe078229-855a-4d1c-83da-4f76d96136f2.mov

### Expected behavior

Show the unique path all the time

### Screenshots

_No response_

### Additional Context

_No response_

### LINKED ISSUE #1752: snippets completion can not input `j`
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu20.04

### Terminal/GUI

gnome-terminal

### AstroNvim Health

```
    1 astronvim: require("astronvim.health").check()
    2 ========================================================================
    3 ## AstroNvim
    4   - INFO: AstroNvim Version: v3.9.0
    5   - INFO: Neovim Version: v0.8.3
    6   - OK: Using stable Neovim >= 0.8.0
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - OK: `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)
   11   - OK: `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - OK: `btm` is installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

I write python code, I want to import `json` module.When I input `im` and press `Tab`, then press `j`,will excape insert mode,instead of enter the visual mode.

### Steps to Reproduce

I have remove all my custom config

### Expected behavior

can input the word `json`,not enter a visual mode.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mehalter**
Fixes #1752 
Fixes #1750

### CODE REVIEW

File: lua/plugins/dap.lua [hunk 1]
```diff
@@ -6,8 +6,8 @@ return {
       "jay-babu/mason-nvim-dap.nvim",
       dependencies = { "nvim-dap" },
       cmd = { "DapInstall", "DapUninstall" },
-      opts = { automatic_setup = true },
-      config = require "plugins.configs.mason-nvim-dap",
+      opts = { handlers = {} },
+      config = require "plugins.configs.mason-nvim-dap", -- remove in v4
```
Comment (jay-babu) [inline lua/plugins/dap.lua:10]: Why can't this be removed now?

Comment (mehalter) [reply lua/plugins/dap.lua:10]: I suppose we can remove the line in our configuration and just leave the file. The main thing is to avoid breaking changes to the user if they are using that file and overriding the config function already. Us removing that file will be a breaking change Technically

Comment (luxus) [reply lua/plugins/dap.lua:10]: can we use -- TODO:

Comment (jay-babu) [reply lua/plugins/dap.lua:10]: can keep file and still delete the line
